name: Wormhole
options:
  bundleIdPrefix: com.wormhole
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    ENABLE_USER_SCRIPT_SANDBOXING: YES

targets:
  Wormhole:
    type: application
    platform: iOS
    sources:
      - Wormhole
    settings:
      base:
        INFOPLIST_FILE: Wormhole/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.wormhole.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_IDENTITY: ""
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: Wormhole/Resources/Info.plist
      properties:
        CFBundleDisplayName: Wormhole
        CFBundleName: Wormhole
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSBonjourServices:
          - _wormhole._tcp
        NSLocalNetworkUsageDescription: Wormhole needs to discover and connect to Wormhole daemons on your network.

  WormholeTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - WormholeTests
    dependencies:
      - target: Wormhole
    settings:
      base:
        INFOPLIST_FILE: WormholeTests/Info.plist
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO

schemes:
  Wormhole:
    build:
      targets:
        Wormhole: all
        WormholeTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - WormholeTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
